version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./gradlew assemble
      - run: ./gradlew check
      - deploy:
          command: bash <(curl -s https://copilot-test.blackducksoftware.com/ci/circle2/scripts/upload)
